services:
  db:
    image: postgres:16.3
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  riverui:
    image: ghcr.io/riverqueue/riverui:latest
    container_name: riverui
    ports:
      - "3000:8080"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable&application_name=riverui
