services:
  db:
    image: postgres:16.3
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  riverui:
    image: ghcr.io/riverqueue/riverui:latest
    container_name: riverui
    ports:
      - "3000:8080"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable&application_name=riverui

  objectstore:
    image: localstack/localstack:3.6.0
    container_name: objectstore
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - ./data/localstack:/var/lib/localstack
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d
