-- name: UpsertTheme :one
insert into "themes" (
  "extension_id",
  "path",
  "name", 
  "display_name",
  "editor_background",
  "editor_foreground",
  "activity_bar_background",
  "activity_bar_foreground",
  "activity_bar_in_active_foreground",
  "activity_bar_border",
  "activity_bar_active_border",
  "activity_bar_active_background",
  "activity_bar_badge_background",
  "activity_bar_badge_foreground",
  "tabs_container_background",
  "tabs_container_border",
  "status_bar_background",
  "status_bar_foreground",
  "status_bar_border",
  "tab_active_background",
  "tab_inactive_background",
  "tab_active_foreground",
  "tab_border",
  "tab_active_border",
  "tab_active_border_top",
  "title_bar_active_background",
  "title_bar_active_foreground",
  "title_bar_border"
)
values (
  @extension_id, 
  @path, 
  @name, 
  @display_name,
  @editor_background,
  @editor_foreground,
  @activity_bar_background,
  @activity_bar_foreground,
  @activity_bar_in_active_foreground,
  @activity_bar_border,
  @activity_bar_active_border,
  @activity_bar_active_background,
  @activity_bar_badge_background,
  @activity_bar_badge_foreground,
  @tabs_container_background,
  @tabs_container_border,
  @status_bar_background,
  @status_bar_foreground,
  @status_bar_border,
  @tab_active_background,
  @tab_inactive_background,
  @tab_active_foreground,
  @tab_border,
  @tab_active_border,
  @tab_active_border_top,
  @title_bar_active_background,
  @title_bar_active_foreground,
  @title_bar_border
)
on conflict("extension_id", "path") do update set
  "name" = excluded."name",
  "display_name" = excluded."display_name",
  "editor_background" = excluded."editor_background",
  "editor_foreground" = excluded."editor_foreground",
  "activity_bar_background" = excluded."activity_bar_background",
  "activity_bar_foreground" = excluded."activity_bar_foreground",
  "activity_bar_in_active_foreground" = excluded."activity_bar_in_active_foreground",
  "activity_bar_border" = excluded."activity_bar_border",
  "activity_bar_active_border" = excluded."activity_bar_active_border",
  "activity_bar_active_background" = excluded."activity_bar_active_background",
  "activity_bar_badge_background" = excluded."activity_bar_badge_background",
  "activity_bar_badge_foreground" = excluded."activity_bar_badge_foreground",
  "tabs_container_background" = excluded."tabs_container_background",
  "tabs_container_border" = excluded."tabs_container_border",
  "status_bar_background" = excluded."status_bar_background",
  "status_bar_foreground" = excluded."status_bar_foreground",
  "status_bar_border" = excluded."status_bar_border",
  "tab_active_background" = excluded."tab_active_background",
  "tab_inactive_background" = excluded."tab_inactive_background",
  "tab_active_foreground" = excluded."tab_active_foreground",
  "tab_border" = excluded."tab_border",
  "tab_active_border" = excluded."tab_active_border",
  "tab_active_border_top" = excluded."tab_active_border_top",
  "title_bar_active_background" = excluded."title_bar_active_background",
  "title_bar_active_foreground" = excluded."title_bar_active_foreground",
  "title_bar_border" = excluded."title_bar_border",
  "updated_at" = now()
returning *;