version: "3"

env: 
  DB_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable

tasks:
  info:
    desc: Run the info command
    deps:
      - build
    env:
      PATH: "$PATH:"
    cmds:
      - npx vscodethemes info -d ../data/jobs/98/sdras.night-owl

  images:
    desc: Run the image command
    deps:
      - build
    env:
      PATH: "$PATH:"
    cmds:
      - npx vscodethemes images -d ../data/jobs/98/sdras.night-owl --path "./themes/Night Owl-color-theme.json"  --label "Night Owl" --uiTheme "vs-dark" --output ../data/jobs/98/sdras.night-owl/images

  build:
    desc: Compile TypesScropt files
    cmds:
      - npm run build
  
  lint:
    desc: Run ESLint
    cmds:
      - npm run lint
      