// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: extension_queries.sql

package db

import (
	"context"
)

const listExtensions = `-- name: ListExtensions :many
SELECT id, vsc_extension_id, name, display_name, short_description, publisher_id, publisher_name, publisher_display_name, installs, trending_daily, trending_weekly, trending_monthly, weighted_rating, published_at, released_at, created_at, updated_at FROM extensions
`

func (q *Queries) ListExtensions(ctx context.Context) ([]Extension, error) {
	rows, err := q.db.Query(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extension
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.ID,
			&i.VscExtensionID,
			&i.Name,
			&i.DisplayName,
			&i.ShortDescription,
			&i.PublisherID,
			&i.PublisherName,
			&i.PublisherDisplayName,
			&i.Installs,
			&i.TrendingDaily,
			&i.TrendingWeekly,
			&i.TrendingMonthly,
			&i.WeightedRating,
			&i.PublishedAt,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
